version: '3.1'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_ENV_1: REAL_VALUE_1
      NEXT_PUBLIC_ENV_2: REAL_VALUE_2
